/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShortcutsRouteImport } from './routes/shortcuts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KontekstNameRouteImport } from './routes/kontekst.$name'

const ShortcutsRoute = ShortcutsRouteImport.update({
  id: '/shortcuts',
  path: '/shortcuts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KontekstNameRoute = KontekstNameRouteImport.update({
  id: '/kontekst/$name',
  path: '/kontekst/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/shortcuts': typeof ShortcutsRoute
  '/kontekst/$name': typeof KontekstNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/shortcuts': typeof ShortcutsRoute
  '/kontekst/$name': typeof KontekstNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/shortcuts': typeof ShortcutsRoute
  '/kontekst/$name': typeof KontekstNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/shortcuts' | '/kontekst/$name'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/shortcuts' | '/kontekst/$name'
  id: '__root__' | '/' | '/shortcuts' | '/kontekst/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShortcutsRoute: typeof ShortcutsRoute
  KontekstNameRoute: typeof KontekstNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shortcuts': {
      id: '/shortcuts'
      path: '/shortcuts'
      fullPath: '/shortcuts'
      preLoaderRoute: typeof ShortcutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontekst/$name': {
      id: '/kontekst/$name'
      path: '/kontekst/$name'
      fullPath: '/kontekst/$name'
      preLoaderRoute: typeof KontekstNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShortcutsRoute: ShortcutsRoute,
  KontekstNameRoute: KontekstNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
